repos:
    - repo: https://github.com/PyCQA/pylint
      rev: pylint-v3.2.7  # Use the sha / tag you want to point at
      hooks:
      - id: pylint
        exclude: ^server/
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v2.3.1  # Use the sha / tag you want to point at
      hooks:
      - id: autopep8
        exclude: ^server/
